### ISSUE TITLE
Style manager is not working

### ISSUE THREAD

**Issue by throne1986** [code-dexterous/grapesjs-example-react#1]
Hi bro,

I have cloned your repo and tested everything else is okay, but when I add text there is no style manager loaded, what is wrong here?

**Comment by code-dexterous** [comment]
@throne1986 I didn't push the latest code. Please check it again.

**Comment by throne1986** [comment]
Ok how can I make blocks by default closed?

**Comment by code-dexterous** [comment]
This has been noted, I will make video on this.

**Comment by code-dexterous** [comment]
@throne1986 New Video released on the above issue.  https://www.youtube.com/watch?v=R45czM-UISQ

**Comment by throne1986** [comment]
Thanks for the tutorial
